### ISSUE TITLE
Docker installation does not work

### ISSUE THREAD

**Issue by ricardochaves** [akamai/cli-cps#74]
Dockerfile
```
FROM python:3.13-alpine3.20

RUN pip install edgegrid-python

WORKDIR /app
```

docker-compose.yml
```
services:
  akamai-cli:
    build: .
    volumes:
      - .:/app
```

```bash
> docker compose run --rm akamai-cli sh
```

Inside a container
```sh
> akamai
sh: akamai: not found
```

Do you have any examples of how to run this in a container?

I'm running docker on `Apple M2 Pro`
